//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transport.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int DestinationId { get; set; }
        public int Source { get; set; }
        public int Target { get; set; }
        public double Destination1 { get; set; }
    }
}
